# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [5]:
x=np.array(my_list)
x
type(x)
x.dtype
#In case of array objects please use dtype method, it discovers all the info about
# the array object

dtype('int32')

In [8]:
r=np.array(["Hi","Hello","Good"])
print(r.dtype)

t=np.array(["Hi",123,123.123])
t.dtype

<U5


dtype('<U7')

In [15]:
my_matrix = [[5,55,555],[6,66,666],[7,77,777],[8,88,888]]
my_matrix

[[5, 55, 555], [6, 66, 666], [7, 77, 777], [8, 88, 888]]

In [16]:
np.array(my_matrix)
#Can check the code while removing any element inside te My_matrix.

array([[  5,  55, 555],
       [  6,  66, 666],
       [  7,  77, 777],
       [  8,  88, 888]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [20]:
import numpy as np

x=np.arange(1,51)
x




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [22]:
x=np.arange(5500,5551)
x

array([5500, 5501, 5502, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510,
       5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518, 5519, 5520, 5521,
       5522, 5523, 5524, 5525, 5526, 5527, 5528, 5529, 5530, 5531, 5532,
       5533, 5534, 5535, 5536, 5537, 5538, 5539, 5540, 5541, 5542, 5543,
       5544, 5545, 5546, 5547, 5548, 5549, 5550])

In [31]:
#Stepping
np.arange(100,151,2)

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

### zeros and ones

Generate arrays of zeros or ones

In [37]:
x=np.zeros((8,9),dtype="int")
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.zeros((5,5))

In [38]:
np.ones((8,9),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
x1=np.ones((5,5))
x1

## eye

Creates an identity matrix

In [ ]:
np.eye(10,10)

In [39]:
np.eye(12, 12,dtype=int)*555

array([[555,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, 555,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0, 555,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0, 555,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 555,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0, 555,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0, 555,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 555,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 555,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 555,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 555,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 555]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [51]:
np.random.rand(5,5)

array([[0.09394672, 0.18862315, 0.3235366 , 0.63139736, 0.62493113],
       [0.40272654, 0.74853624, 0.4350735 , 0.62109482, 0.08554549],
       [0.72929163, 0.36247455, 0.54147633, 0.06204167, 0.85681337],
       [0.82513271, 0.61101899, 0.82940393, 0.30677547, 0.7622002 ],
       [0.6236323 , 0.86108868, 0.05891671, 0.03679537, 0.23859758]])

In [49]:
np.random.rand(7,6,5)#(Number of individual matrixes,number of rows,number of columns)

array([[[0.59724082, 0.90382318, 0.96098639, 0.09492863, 0.99217687],
        [0.64867482, 0.63006291, 0.51223678, 0.89028374, 0.34726438],
        [0.71630333, 0.8528789 , 0.18078505, 0.80134708, 0.49206469],
        [0.50177452, 0.45858461, 0.37324681, 0.75658012, 0.73978518],
        [0.20366537, 0.63357741, 0.35556398, 0.51929757, 0.79211879],
        [0.91199796, 0.45789084, 0.63361916, 0.24359391, 0.9788403 ]],

       [[0.48190077, 0.66416897, 0.99084092, 0.7975562 , 0.87053639],
        [0.59483846, 0.43002221, 0.04542544, 0.84064634, 0.89591277],
        [0.41384035, 0.792972  , 0.79382972, 0.70786418, 0.76368884],
        [0.87966425, 0.81253141, 0.21736883, 0.6397771 , 0.36059244],
        [0.71507282, 0.76816592, 0.44019538, 0.79266361, 0.73050639],
        [0.08157424, 0.51063769, 0.16334703, 0.46968216, 0.97592172]],

       [[0.36402753, 0.05435693, 0.15357401, 0.90066188, 0.18686622],
        [0.77107744, 0.48885707, 0.43527709, 0.15913252, 0.41821306],
        [0.23861

In [ ]:
#np.random.rand(5,5)
import numpy as np

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [72]:
np.random.randint(10,20)

18

In [78]:
np.random.randint(500,1000,size=(7,5))#Matrix
#np.random.randint(500,1000,size=(12,5))#Array

array([[765, 562, 725, 869, 896],
       [756, 966, 898, 641, 782],
       [759, 508, 780, 630, 645],
       [586, 834, 605, 679, 828],
       [928, 630, 745, 764, 707],
       [900, 618, 877, 901, 735],
       [621, 788, 826, 532, 609]])

In [74]:
np.random.randint(500,1000)

794

In [75]:
np.random.uniform(50,100,size=(3,3))

array([[73.09895786, 77.31048621, 89.07533829],
       [99.88558161, 75.83968329, 60.23457373],
       [81.77529783, 83.53577872, 55.12650497]])

In [80]:
rr=np.random.randint(50,150,(10,2))#(row,column,number of elements)
rr

array([[124,  65],
       [ 62, 103],
       [ 78, 102],
       [ 55, 118],
       [ 65,  93],
       [127,  87],
       [ 93, 138],
       [124,  57],
       [ 87,  74],
       [ 70, 117]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [79]:
arr = np.arange(25)
ranarr = np.random.randint(50,100,25)   #(start, end, no. of elements)
print(ranarr,"Ranarr - RandInt")
print()
print(arr,"Arr - Arange")

[89 79 85 52 60 89 54 92 53 51 65 52 93 67 64 82 85 69 51 88 83 69 54 75
 65] Ranarr - RandInt

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] Arr - Arange


In [ ]:
arr.shape
ranarr.shape
rr.shape

## Reshape
Returns an array containing the same data with a new shape.

In [81]:
print(np.arange(100).reshape(10,10),"\n")
print(np.arange(100).reshape(20,5),"\n")
print(np.arange(100).reshape(25,4))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
#Try to work with np.min,max
ranarr = np.random.randint(50,100,25)   #(start, end, no. of elements)
ranarr

In [ ]:
print(ranarr)
ranarr.max()#Prints the maximum Number


In [ ]:
print(ranarr)
ranarr.argmax()#It prints the index position of maximum number

In [ ]:
print(ranarr)
ranarr.min()#Prints the minimum Number

In [ ]:
print(ranarr)
ranarr.argmin()#It prints the index position of minimum number

In [ ]:
x=arr.reshape(5,5)
x

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
x.shape

In [ ]:
arr = np.arange(30)
arr = arr.reshape(6,5)
arr

In [ ]:
arr.shape

### dtype

You can also grab the data type of the object in the array:

In [ ]:
x1=["Hello"]
x2="Good Morning"
x3=[123]
x4=123
x5={"a":[55,67,89]}
x6={1,2,3}
x7=np.array([1,2,3,4,5,6,7,8])
x8=np.array(["Hello","Good Morning"])

In [ ]:
type(x7)
x8.dtype

In [ ]:
type(x5)
type(arr)
#Basic Difference between type() and .dtype.
#type() function runs with any data type and it also works with numpy/array objects but with array objects it displays
#half of the infomation like numpy.ndarray
# After getting numpy.ndarray the user can extract much of the knowledge with .dtype
# .dtype only works with numpy/array objects.

# Great Job!