# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr=np.arange(50,150)
arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

In [24]:
#88
#arrrr[38]
#arrrr[61]
#arrrr[-10]

#Tarrsk
#61,86,129,115,138,110,53,102,114,133
arr[11]
arr[36]
arr[79]
arr[65]
arr[88]
arr[60]
arr[3]
arr[52]
arr[64]
arr[83]

arr

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [25]:
arr[10:25] #arr[start:end]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74])

In [27]:
#Get values in a range
#92:145
print(arr[42:96])
print()
#86:136
print(arr[36:87])

#Exercise
#70-117
print(arr[20:68])
print()
#101-140
print()
print(arr[51:91])


[ 92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145]

[ 86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136]
[ 70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87
  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105
 106 107 108 109 110 111 112 113 114 115 116 117]


[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140]


In [ ]:
## Get values in a range
arr[0:5]
arr[-21]

In [29]:
#Stepping
arr[::2]
arr[::-1]
#arr[-1::-1]
#arr[:-21:-1]
#arr[:49:-1]

array([149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138, 137,
       136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124,
       123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111,
       110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100,  99,  98,
        97,  96,  95,  94,  93,  92,  91,  90,  89,  88,  87,  86,  85,
        84,  83,  82,  81,  80,  79,  78,  77,  76,  75,  74,  73,  72,
        71,  70,  69,  68,  67,  66,  65,  64,  63,  62,  61,  60,  59,
        58,  57,  56,  55,  54,  53,  52,  51,  50])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [43]:
#Setting a value with index range (Broadcasting)
import numpy as np
arr=np.arange(100,150)
#Show
arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [31]:
#Single value replacing
new=arr[0:10]
new

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [32]:
new[5]=555
new

array([100, 101, 102, 103, 104, 555, 106, 107, 108, 109])

In [45]:
print(id(arr))
print(id(new))


98981168
98957872


Now note the changes also occur in our original array!

In [46]:
arr_new=np.copy(arr[0:10])
arr_new[:]=555
print(arr_new)
arr

[555 555 555 555 555 555 555 555 555 555]


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [48]:
print(id(arr))
print(id(arr_new))

98981168
98983408


Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr=np.arange(80,100)
arr
arr_copy = arr.copy()
arr_copy=arr_copy[0:20]
arr_copy[:]=55
arr_copy

## Indexing a 2D array (matrices)

In [12]:
import numpy as np

zxc=np.arange(1,31)
zxc=zxc.reshape(5,6)
zxc

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [16]:
#23,25,28
zxc[[3,4,4],[4,0,3]]

array([23, 25, 28])

In [ ]:
zxc[2,2]
#zxc["row","column"]
zxc[3,5]
zxc[4,5]

#10,17,29,26,19
zxc[[1,2,4,4,3,1],[3,4,4,1,0,3]]
#zxc[[row1,row2,row3,row4],[col1,col2,col3,col4]]

In [18]:
#Exercise
abc=np.arange(200,250).reshape(10,5)
abc

#Find 217,227,229,244,211,233,245,248,222,225,202

array([[200, 201, 202, 203, 204],
       [205, 206, 207, 208, 209],
       [210, 211, 212, 213, 214],
       [215, 216, 217, 218, 219],
       [220, 221, 222, 223, 224],
       [225, 226, 227, 228, 229],
       [230, 231, 232, 233, 234],
       [235, 236, 237, 238, 239],
       [240, 241, 242, 243, 244],
       [245, 246, 247, 248, 249]])

In [21]:
abc[[3,5,5,8,2,6,9,9,4,5,0],[2,2,4,4,1,3,0,3,2,0,2]]
zxc

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [31]:
#print(zxc[:,[4,2]],"\n")#only Columns
#zxc[[1,4],:]#Only rows

zxc[:,[5,0,4,3,1,2]]

#zxc[[2,3],:]
zxc

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [30]:
#Print last row and column
print(zxc[4,:],"\n")#row
zxc[:,5]#column

[25 26 27 28 29 30] 



array([ 6, 12, 18, 24, 30])

In [ ]:
zxc

Fancy indexing allows the following

In [ ]:
abc=np.arange(0,100).reshape(10,10)
abc

In [34]:
#Allows in any order
print(abc[[6,4,2,7]])#Extracting any Desired Row With Respect to Index Position Number
print()
print(abc[:,[4,2,3]])#Extracting any Desired Column with Respect to Index Position Number
abc[[6,7,8],:]
abc

[[230 231 232 233 234]
 [220 221 222 223 224]
 [210 211 212 213 214]
 [235 236 237 238 239]]

[[204 202 203]
 [209 207 208]
 [214 212 213]
 [219 217 218]
 [224 222 223]
 [229 227 228]
 [234 232 233]
 [239 237 238]
 [244 242 243]
 [249 247 248]]


array([[200, 201, 202, 203, 204],
       [205, 206, 207, 208, 209],
       [210, 211, 212, 213, 214],
       [215, 216, 217, 218, 219],
       [220, 221, 222, 223, 224],
       [225, 226, 227, 228, 229],
       [230, 231, 232, 233, 234],
       [235, 236, 237, 238, 239],
       [240, 241, 242, 243, 244],
       [245, 246, 247, 248, 249]])

In [ ]:
print(abc[2:7,9])
#90-97
print(abc[9,:8])
#abc[row_start:row_end,column]

print(abc[5,:6])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [35]:
import numpy as np
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
arr[arr<=5]
#arr[arr>=5]

arr[(arr>=5) & (arr<=15)]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
arr[arr >= 4]

bool_arr=arr>=4

In [43]:
bool_arr

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [44]:
print(arr[bool_arr],"\n")

print(arr[arr >= 4])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr[arr>2]

In [ ]:
x = 2
arr[arr>x]

# Great Job!
