##### NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [2]:
#Difference between Arange and array object
import numpy as np
arr = np.arange(0,10)
arr1=np.arange(0,11)
arr2=np.arange(1,101)

In [2]:
print(arr)
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [5]:
arr2.shape

(100,)

In [9]:
arr1.shape
arr.shape

(10,)

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [22]:
# Also warning, but not an error instead infinity
print(arr1)
11/arr1
(np.arange(10,20))/10

[ 0  1  2  3  4  5  6  7  8  9 10]


C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [23]:
arr1**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [24]:
x=np.arange(1,10)
y=np.array(10)
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
10


In [25]:
z=x+y
z
print(x,"X")
print(y,"Y")
print(z,"Z")

[1 2 3 4 5 6 7 8 9] X
10 Y
[11 12 13 14 15 16 17 18 19] Z


In [10]:
#Appending new elements into the existing Numpy Array Object
asd=np.arange(0,10)
asd=np.append(asd,[55,66,77,22,45,44])
asd

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 55, 66, 77, 22, 45, 44])

In [13]:
#Deleting any element in array
sun=np.delete(sun,10)
sun

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 45, 44])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
#Taking Square Roots
np.sqrt(arr)
#arr1
#arr2

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

In [ ]:
np.max(arr) #same as arr.max()
#arr.max()

In [ ]:
np.min(arr)#Same as arr.min()
#arr.min()

In [30]:
np.sin(arr)#Sin Thetha
np.cos(arr)#Cos Thetha

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [26]:
np.log(arr1)

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
np.mean(arr) #Mean

In [ ]:
np.median(arr) #Median

In [ ]:
np.std(arr) #standard Deviation

In [ ]:
np.var(arr) #Variance

# Great Job!

That's all we need to know for now!