# Logistic Regression

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#Data Analysis nsmallest(),nlargest()
#tail()
#head()

## Importing the dataset

In [22]:
dataset = pd.read_csv('C:/Users/admin/IBM_Training/Training/ML Algorithms/Social_Network_Ads.csv')
dataset.head()


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [23]:
x = dataset.iloc[:, :-1]
y = dataset.iloc[:, -1]

In [6]:
x

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

## Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3,random_state=52)

In [8]:
x_train

Age  EstimatedSalary
41    33            51000
115   40            57000
85    31           118000
308   36           125000
194   28            89000
..   ...              ...
86    24            55000
151   41            45000
13    32            18000
267   37            74000
156   46            59000

[280 rows x 2 columns]

## Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [26]:
x_test

array([[-0.97854158, -0.47975379],
       [-0.00486837, -0.45024561],
       [-1.75748016,  0.16942612],
       [ 0.38460092, -0.53877015],
       [ 0.77407021, -1.42401548],
       [-1.46537819, -1.27647459],
       [ 1.06617217, -1.09942552],
       [-0.39433765, -0.03713112],
       [-0.68643962,  0.25795065],
       [ 0.48196824,  0.28745883],
       [-1.0759089 ,  0.28745883],
       [ 1.06617217,  0.11040977],
       [-1.56274551, -0.0666393 ],
       [-1.17327623,  0.25795065],
       [ 0.38460092,  0.25795065],
       [ 0.18986628,  1.88090043],
       [-0.00486837,  0.28745883],
       [ 0.18986628, -0.27319655],
       [ 1.16353949,  0.55303243],
       [ 0.09249896,  0.28745883],
       [ 0.38460092,  0.05139341],
       [ 0.87143753, -1.42401548],
       [ 0.38460092,  0.28745883],
       [-0.49170497,  1.91040861],
       [-0.00486837, -1.09942552],
       [-0.78380694,  0.37598337],
       [ 0.2872336 , -0.15516383],
       [ 1.06617217,  1.7923759 ],
       [-0.39433765,

In [ ]:
print(x_train)

## Training the Logistic Regression model on the Training set

In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

LogisticRegression()

## Predicting a new result

In [48]:
#print(classifier.predict(sc.transform([[30,87000]])))  # After Standardization
print(classifier.predict(sc.transform([[19,50000]])))  # After Normalization
#print(classifier.predict([[,]]))# No Standardiation and Normalization

[0]


In [13]:
np.array(y_test)

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

## Predicting the Test set results

In [28]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

## Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("\n",accuracy_score(y_test, y_pred))
print("\n",classification_report(y_test,y_pred))



[[69  4]
 [15 32]]

 0.8416666666666667

               precision    recall  f1-score   support

           0       0.82      0.95      0.88        73
           1       0.89      0.68      0.77        47

    accuracy                           0.84       120
   macro avg       0.86      0.81      0.83       120
weighted avg       0.85      0.84      0.84       120



# Great Job!